### ISSUE TITLE
Incompatibility with asciidoctor 2.0.x

### ISSUE THREAD

**Issue by rillbert** [jirutka/asciidoctor-rouge#12]
It seems that asciidoctor-rouge and the latest asciidoctor (v2.0.3) are incompatible due to some change in the passthrough member in the asciidoctor `node`.

I try to generate the user-manual.adoc from the asciidoctor.org repo with the following command:

`asciidoctor --trace -r asciidoctor-rouge -a source-highlighter=rouge ../asciidoctor.org/docs/user-manual.adoc`

The command hangs and when interrupted with ctrl-c, I get the following stacktrace:

`Traceback (most recent call last):
	38: from /home/anders/.rbenv/versions/2.6.1/bin/asciidoctor:23:in `<main>'
	37: from /home/anders/.rbenv/versions/2.6.1/bin/asciidoctor:23:in `load'
	36: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/bin/asciidoctor:15:in `<top (required)>'
	35: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/cli/invoker.rb:109:in `invoke!'
	34: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/cli/invoker.rb:109:in `each'
	33: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/cli/invoker.rb:126:in `block in invoke!'
	32: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor.rb:1519:in `convert_file'
	31: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor.rb:1519:in `open'
	30: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor.rb:1519:in `block in convert_file'
	29: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor.rb:1411:in `convert'
	28: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor.rb:1302:in `load'
	27: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/document.rb:556:in `parse'
	26: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/document.rb:556:in `each'
	25: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/document.rb:557:in `block in parse'
	24: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/document.rb:557:in `[]'
	23: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge/treeprocessor.rb:46:in `process'
	22: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:168:in `find_by'
	21: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:472:in `find_by_internal'
	20: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:472:in `each'
	19: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:474:in `block in find_by_internal'
	18: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `find_by_internal'
	17: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `each'
	16: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:499:in `block in find_by_internal'
	15: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `find_by_internal'
	14: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `each'
	13: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:499:in `block in find_by_internal'
	12: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `find_by_internal'
	11: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `each'
	10: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:499:in `block in find_by_internal'
	 9: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `find_by_internal'
	 8: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `each'
	 7: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:499:in `block in find_by_internal'
	 6: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `find_by_internal'
	 5: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:497:in `each'
	 4: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:499:in `block in find_by_internal'
	 3: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.3/lib/asciidoctor/abstract_block.rb:442:in `find_by_internal'
	 2: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge/treeprocessor.rb:47:in `block in process'
	 1: from /home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge/treeprocessor.rb:111:in `process_listing'
/home/anders/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/asciidoctor-rouge-0.4.0/lib/asciidoctor/rouge/passthroughs_substitutor.rb:37:in `restore': asciidoctor: FAILED: /home/anders/repos/asciidoctor.org/docs/user-manual.adoc: Failed to load AsciiDoc document - undefined method `passthroughs' for #<Asciidoctor::Block:0x0000556b333d4098> (NoMethodError)
`

Regards
/Anders

**Comment by Carin1221** [comment]
I'd like to add to this as well. I had some incompatibility issues with Asciidoctor 2.0.10.
Not quite this issue in specific but using an earlier version of Asciidoctor did, indeed, resolve my issue.

**Comment by ghost** [comment]
I am also running into issues. It doesn't crash, but with v2 it actually outputs the HTML code inside the code tag with weird styling. Using asciidoctor < v2 resolves this, will this get fixed? **Or is this project dead and we should move on?**

Screenshot using the asciidoctor sample:
![image](https://user-images.githubusercontent.com/51907712/76410451-3c84d480-6390-11ea-8980-39801030f499.png)

**Comment by Carin1221** [comment]
@ldz-w It's been a hot minute since the last commit. I continue to use asciidoctor-rouge but only with asciidoctor < v2.
I'm *not* expecting any further updates; I'd move on if you're not willing / able to use < v2.

**Comment by ghost** [comment]
@Legio1221 Alright, thanks. Appreciate the answer.

**Comment by jirutka** [comment]
Asciidoctor added builtin support for Rouge in [version 2.0.0](https://github.com/asciidoctor/asciidoctor/blob/master/CHANGELOG.adoc#200-2019-03-22---mojavelinux), so this extension is not needed anymore.
