### ISSUE TITLE
asciidoctor-pdf convergence

### ISSUE THREAD

**Issue by habamax** [jirutka/asciidoctor-rouge#3]
Is it possible to alias or rename `rouge-theme` to `rouge-style`?

Currently asciidoctor-pdf has the rouge highlighter and it uses `rouge-style` attribute:

https://github.com/asciidoctor/asciidoctor-pdf/issues/876

I think it would be good to have the same attribute name to avoid:

:source-highlighter: rouge
:rouge-theme: github
:rouge-style: github

In a document that is intended to produce html and pdf.

**Comment by jirutka** [comment]
That’s a good point! However, `rouge-style` would be inconsistent with Asciidoctor; there is `highlightjs-theme`, `prettify-theme`, and `pygments-style`. That’s 2:1, moreover Pygments is obsolete.

I’d personally prefer `rouge-style`, but I wanted to be consistent with Asciidoctor… 😞

I can add `pygments-style` as alias for `pygments-theme`, but maybe @mojavelinux should add an opposite alias to asciidoctor-pdf to be consistent with Asciidoctor (core). ;)

**Comment by habamax** [comment]
I will be content with any variant that will let me specify rouge theme/style once.

@mojavelinux, what do you think?

**Comment by jirutka** [comment]
ping @mojavelinux
