### ISSUE TITLE
Highlighting in a table cell does not work

### ISSUE THREAD

**Issue by chickenkiller** [jirutka/asciidoctor-rouge#4]
I made a sample asciidoc file with the following content:

````
Highlighting test
=================

.This is a normal code block
[source, c]
-----
int main(int argv, char** argv) {
  return 0;
}
-----

[cols="a"]
|=================
| This is a normal cell text
|
.This is a code block in a table cell
[source, c]
-----
int main(int argv, char** argv) {
  return 0;
}
-----
|=================
````

1. When I call
````
asciidoctor -a source-highlighter=pygments test_highlight.adoc
````
both code blocks (outside and inside the table) are highlighted.

2. When I call
````
asciidoctor -r asciidoctor-rouge -a source-highlighter=rouge test_highlight.adoc
````
Only the block ouside the table is highlighted. So we have a different behaviour. I suppose it is due to asciidoctor-rouge being an extension...

How can we fix this?

Thanks in advance
Lionel

**Comment by jirutka** [comment]
This is IMO a bug in `Asciidoctor::Document#find_by`, it does not search inside table cells.

I’ve implemented a workaround in 277d5b275087130e618f16355828033c8756a6e5, please try `dev` branch.

/cc @mojavelinux

**Comment by mojavelinux** [comment]
The table model isn't really designed for traversal at the moment (as that was not the original goal of the table model). However, AsciiDoc table cells are a special case and I do believe we should have some way to easily discover those. Most of the time, that's what you need find_by to find in a table anyway.

Note that Asciidoctor Mathematical uses a similar workaround.

**Comment by jirutka** [comment]
@mojavelinux Thanks for clarification. So there's currently not any better way than iterating over each cell of every table?

**Comment by mojavelinux** [comment]
Not that I'm aware of. I've created an issue in core to track this shortcoming. https://github.com/asciidoctor/asciidoctor/issues/2524

**Comment by mojavelinux** [comment]
But more to the point of this extension, the source highlighter needs to be made into extension point so that it's not necessary to walk the document at all. There have been numerous requests to integrate different highlighters (or in different ways) and it's really something core should be delegating out. That should be the focus of the rouge integration into core.

**Comment by mojavelinux** [comment]
:+1:

**Comment by chickenkiller** [comment]
Thanks, I'll give this a try in a day or two !
