### ISSUE TITLE
 Failed to load AsciiDoc document - undefined method `conum_font_color' for nil:NilClass

### ISSUE THREAD

**Issue by eiswind** [jirutka/asciidoctor-rouge#6]
I am running the extension with JRuby and AsciidoctorJ.
I set the rouge-css to style and get the above error.

Please let me know if I can do anything to help to investigate this. It would be really great if I could use the extension with reveal and epub so I can get consistent style on all outputs.

**Comment by jirutka** [comment]
I have no idea - there's no such method in this extension, rouge or asciidoctor. I found it just in asciidoctor-pdf.

**Comment by eiswind** [comment]
Indeed you had the idea, I got asciidoctor-pdf mixed up with your extension, that lead to the error.
Thanks ! Im struggling with some background color issues now, but I guess I can figure that out.
